
server.port: 8080

# Token Relay filter: https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#the-tokenrelay-gatewayfilter-factory
spring:
  security:
    oauth2:
      client:
        registration:
          gateway-client:
            client-id: "gateway-client-id"
            client-secret: "secret"
            client-authentication-method: "client_secret_basic"
            authorization-grant-type: "authorization_code"
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/gateway-client-id"
            scope: "openid, profile"
            provider: "auth-server"
        provider:
          auth-server:
            issuer-uri: "http://localhost:8081"
