server.port: 8081

spring:
  security:
    oauth2:
      authorizationserver:
        client:
          gateway-client:
            registration:
              client-id: "gateway-client-id"
              client-secret: "{noop}secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/login/oauth2/code/gateway-client-id"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: false
    user:
      name: "admin"
      password: "{noop}admin"
      role:
        - ADMIN
